name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python for static code analysis (optional step for Python-based apps)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Install required dependencies for static code analysis (like pylint)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt  # Install all dependencies from requirements.txt

      # Run static code analysis with pylint (or another tool of your choice)
      - name: Run static code analysis (pylint)
        run: |
          pylint **/*.py

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t todo-app .

      # Run Trivy to scan the Docker image for vulnerabilities
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image: todo-app
          format: 'table'

      # Push the Docker image to a container registry (e.g., Docker Hub or GitHub Container Registry)
      # Uncomment and configure the below lines if you're pushing to a registry
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker push todo-app
